services:
  caddy:
    image: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy-server/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

  mylandscape:
    build: .
    image: mylandscape
    container_name: mylandscape
    restart: unless-stopped
    hostname: mylandscape
    ports:
      - "8888:80/tcp"

volumes:
  caddy_data:
  caddy_config: